### ISSUE TITLE
支持 wasm 吗，哥？

### ISSUE THREAD

**Issue by pzhasaki** [svg-rust/svgo-rs#10]
支持 wasm 吗，哥？
看着像打包成 node 规范？目录结构没太懂，有时间麻烦能写一下文档嘛

**Comment by SyMind** [comment]
@pzhasaki 之后是能够支持的，但是目前这个项目还在非常初期的阶段。
我预计明年2月会重新规划这个项目，并完善文档。

**Comment by pzhasaki** [comment]
好滴 感谢

**Comment by Zxilly** [comment]
有进一步的进展吗？
